name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.5
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to EC2
        run: scp -i /path/to/your/key.pem /path/to/your/P7_script.py ubuntu@your-ec2-instance-ip:/path/to/destination



        # Write commands here to deploy your model to SageMaker using AWS CLI
