<<<<<<< HEAD
name: Deploy to AWS EC2
=======
name: Deploy to EC2
>>>>>>> 34ce8a03c63e4903011b085693d44f95b3b1cf44

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
<<<<<<< HEAD
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: <Your AWS region>

    - name: Deploy model to EC2
      run: aws s3 cp /Users/soneitaraherimalala/Desktop/oc-P7/source/P7_script.py s3://oc-p7/
=======
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to EC2
        run: scp -i /Users/soneitaraherimalala/Desktop/oc-P7/key-pair.pem /Users/soneitaraherimalala/Desktop/P7/P7_script.py ubuntu@35.180.97.44:/home/ubuntu

>>>>>>> 34ce8a03c63e4903011b085693d44f95b3b1cf44


        # Write commands here to deploy your model to SageMaker using AWS CLI
