name: Set up SSH and Run Tests

on:
  push:
    branches:
      - main

jobs:
  deploy_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH dependencies
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          sudo apt-get update -y && sudo apt-get install rsync openssh-client
          eval $(ssh-agent -s)
          echo -e "Host *\\n\\tStrictHostKeyChecking no\\n\\n" > ~/.ssh/config
          sudo chmod 400 oc-P7linux.pem
          cat oc-P7linux.pem
          cat oc-P7linux.pem | ssh-add -
          echo "35.180.190.64" > ~/.ssh/known_hosts

      - name: Deploy code on remote server
        run: |
          sudo chmod 600 oc-P7linux.pem
          rsync -avz -e "ssh -i oc-P7linux.pem" --exclude '.git/*' --exclude 'node_modules/*' --exclude '.env'  ./ ubuntu@35.180.190.64:/home/ubuntu/deploygitlabci

      - name: Launch script
        run: |
          ssh -i oc-P7linux.pem ubuntu@35.180.190.64 'cd /home/ubuntu/oc-P7/source && ls -al'

      - name: Install Python dependencies and pytest on remote server
        run: |
          ssh -i oc-P7linux.pem ubuntu@35.180.190.64 'sudo apt-get update && sudo apt-get install -y python3-pip'
          ssh -i oc-P7linux.pem ubuntu@35.180.190.64 'python3 -m pip install --upgrade pip'
          ssh -i oc-P7linux.pem ubuntu@35.180.190.64 'python3 -m pip install pytest'

      - name: Install Pytest on remote server
        run: |
          ssh -i oc-P7linux.pem ubuntu@35.180.190.64 'python3 -m pip install pytest'

     

          
         
          

          






