name: Deploy to EC2

on:
  push:
    branches:
      - main  # ou la branche de votre choix

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2


    - name: Copy files to EC2
      run: |
        cat oc-P7linux.pem
        # rsync -avz -e "ssh -o StrictHostKeyChecking=no -i oc-P7linux.pem " --exclude '.git/*' --exclude 'node_modules/*' --exclude '.env'  ./ ubuntu@35.180.190.64:/home/ubuntu/deploy

    - name: Deploy on EC2
      run: |
        # ssh -i test.pem ubuntu@${{ secrets.EC2_IP }} 'cd /home/ubuntu/oc-P7/source && ls -al'
        ssh -i oc-P7linux.pem ubuntu@$35.180.190.64 'cd /home/ubuntu/deploy && ls -al'
