name: Deploy to EC2

on:
  push:
    branches:
      - main  # ou la branche de votre choix

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

        # - name: Setup SSH
        #uses: webfactory/ssh-agent@v0.5.3
        #with:
        #ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Copy files to EC2
      run: |
        rsync -avz --exclude '.git/*' --exclude 'node_modules/*' --exclude '.env' "ssh -i test.pem" ./ ubuntu@35.180.190.64:/home/ubuntu/oc-P7/source
        #rsync -avz --exclude '.git/*' --exclude 'node_modules/*' --exclude '.env' "ssh -i test.pem" ./ ubuntu@${{ secrets.EC2_IP }}:/home/ubuntu/oc-P7/source

    - name: Deploy on EC2
      run: |
        # ssh -i test.pem ubuntu@${{ secrets.EC2_IP }} 'cd /home/ubuntu/oc-P7/source && ls -al'
        ssh -i test.pem ubuntu@$35.180.190.64 'cd /home/ubuntu/oc-P7/source && ls -al'
