name: Set up SSH and deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH and deploy
        uses: appleboy/ssh-action@master
        with:
          host: 35.180.190.64
          username: ubuntu  # Assurez-vous que le nom d'utilisateur est correct
          key: ${{ secrets.OC }}
          port: 22
          script: |
             rsync -avz -e "ssh -o StrictHostKeyChecking=no -i oc-P7linux.pem " --exclude '.git/*' --exclude 'node_modules/*' --exclude '.env'  ./ ubuntu@35.180.190.64:/home/ubuntu/deploy 



